export const ADD_TODO = 'ADD_TODO'; 
export const TOGGLE_TODO = 'TOGGLE_TODO'; 
export const REMOVE_TODO = 'REMOVE_TODO'; 
export const CLEAR_TODOS = 'CLEAR_TODOS'; 
export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCESS = 'FETCH_TODOS_SUCESS';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';
export const PROCESSING_REQUEST = 'PROCESSING_REQUEST';